version: '2.4'

services:
  pokemonapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - pokemondb
  pokemondb:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: skruve512
      POSTGRES_DB: pokemondb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: 
    driver: local