version: '3.9'

services:

  pokemon-db:
    image: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: skruve512
      POSTGRES_DB: pokemondb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
    driver: local